
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynet
  db:
    image: cockroachdb/cockroach
    ports:
     - "26257:26257"
     - "8080:8080"
    command: start-single-node --insecure
    environment:
      DB_USER: sibuh
      DB_PASSWORD: sibuh
      DB_NAME: rrooms
    volumes:
      - dbvolume:/cockroach/cockroach-data
    networks:
      - mynet

volumes:
  dbvolume:
networks:
  mynet: