
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet
  db:
    image: cockroachdb/cockroach
    ports:
     - "26257:26257"
     - "8080:8080"
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 5s
      timeout: 30s
      retries: 6
      start_period: 10s
    environment:
      DB_USER: sibuh
      DB_PASSWORD: sibuh
      DB_NAME: reservation
    volumes:
      - dbvolume:/cockroach/cockroach-data
    networks:
      - mynet

volumes:
  dbvolume:
networks:
  mynet:
    driver: bridge