// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hotel struct {
	ID        pgtype.UUID
	Name      string
	Star      pgtype.Int4
	Location  []float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Room struct {
	ID         pgtype.UUID
	RoomNumber string
	UserID     pgtype.UUID
	HotelID    pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
