// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateHotel(ctx context.Context, arg CreateHotelParams) (Hotel, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, email string) (User, error)
	HoldRoom(ctx context.Context, arg HoldRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
