// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :one
insert into reservations (room_id,user_id,status,from_time,to_time)
values($1,$2,$3,$4,$5) 
returning id, room_id, user_id, status, from_time, to_time
`

type CreateReservationParams struct {
	RoomID   pgtype.UUID
	UserID   pgtype.UUID
	Status   ReservationStatus
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.RoomID,
		arg.UserID,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Status,
		&i.FromTime,
		&i.ToTime,
	)
	return i, err
}

const updateReservation = `-- name: UpdateReservation :one
update reservations set status=$1 where id =$2 returning id, room_id, user_id, status, from_time, to_time
`

type UpdateReservationParams struct {
	Status ReservationStatus
	ID     pgtype.UUID
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservation, arg.Status, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Status,
		&i.FromTime,
		&i.ToTime,
	)
	return i, err
}
