// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const holdRoom = `-- name: HoldRoom :one
update rooms set status ='HELD',user_id =$1 
where id= $2 and hotel_id =$3 
returning id, room_number, user_id, hotel_id, created_at, updated_at
`

type HoldRoomParams struct {
	UserID  pgtype.UUID
	ID      pgtype.UUID
	HotelID pgtype.UUID
}

func (q *Queries) HoldRoom(ctx context.Context, arg HoldRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, holdRoom, arg.UserID, arg.ID, arg.HotelID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.UserID,
		&i.HotelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
