// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room_type.sql

package db

import (
	"context"
)

const createRoomType = `-- name: CreateRoomType :one
INSERT INTO 
room_types (room_type,description,price,capacity) 
VALUES($1,$2,$3,$4)
RETURNING id, room_type, price, description, capacity, created_at, updated_at, deleted_at
`

type CreateRoomTypeParams struct {
	RoomType    Roomtype `json:"room_type"`
	Description string   `json:"description"`
	Price       float64  `json:"price"`
	Capacity    int32    `json:"capacity"`
}

func (q *Queries) CreateRoomType(ctx context.Context, arg CreateRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, createRoomType,
		arg.RoomType,
		arg.Description,
		arg.Price,
		arg.Capacity,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.RoomType,
		&i.Price,
		&i.Description,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
