// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: room_types.sql

package db

import (
	"context"
)

const addRoomType = `-- name: AddRoomType :one
insert into room_types(room_type,price,description,capacity)values($1,$2,$3,$4) returning id, room_type, price, description, capacity, created_at, updated_at, deleted_at
`

type AddRoomTypeParams struct {
	RoomType    Roomtype `json:"room_type"`
	Price       float64  `json:"price"`
	Description string   `json:"description"`
	Capacity    int32    `json:"capacity"`
}

func (q *Queries) AddRoomType(ctx context.Context, arg AddRoomTypeParams) (RoomType, error) {
	row := q.db.QueryRow(ctx, addRoomType,
		arg.RoomType,
		arg.Price,
		arg.Description,
		arg.Capacity,
	)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.RoomType,
		&i.Price,
		&i.Description,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
