// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoom = `-- name: AddRoom :one
insert into rooms(room_number,hotel_id,room_type_id,floor)values($1,$2,$3,$4) returning id, room_number, hotel_id, room_type_id, floor, status, created_at, updated_at
`

type AddRoomParams struct {
	RoomNumber int32       `json:"room_number"`
	HotelID    pgtype.UUID `json:"hotel_id"`
	RoomTypeID pgtype.UUID `json:"room_type_id"`
	Floor      string      `json:"floor"`
}

func (q *Queries) AddRoom(ctx context.Context, arg AddRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, addRoom,
		arg.RoomNumber,
		arg.HotelID,
		arg.RoomTypeID,
		arg.Floor,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.HotelID,
		&i.RoomTypeID,
		&i.Floor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
select
r.id, r.room_number, 
r.hotel_id, r.room_type_id, 
r.floor, r.status, 
r.created_at, r.updated_at,
rt.price
from rooms r 
join room_types rt on r.room_type_id=rt.id
where r.id =$1
`

type GetRoomRow struct {
	ID         pgtype.UUID        `json:"id"`
	RoomNumber int32              `json:"room_number"`
	HotelID    pgtype.UUID        `json:"hotel_id"`
	RoomTypeID pgtype.UUID        `json:"room_type_id"`
	Floor      string             `json:"floor"`
	Status     RoomStatus         `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Price      float64            `json:"price"`
}

func (q *Queries) GetRoom(ctx context.Context, id pgtype.UUID) (GetRoomRow, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i GetRoomRow
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.HotelID,
		&i.RoomTypeID,
		&i.Floor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Price,
	)
	return i, err
}

const searchRoom = `-- name: SearchRoom :many
select id, room_number, hotel_id, room_type_id, floor, status, created_at, updated_at from rooms 
where price < $1 
and hotel_id in (select id from hotels where ST_DWithin(location, ST_GeogPoint($2, $3), 1000))
and roon_id not in(select id from reservations where from_time between $4 and $5 or to_time between $4 and $5)
and $6 =(select room_type from room_types where id=room_type_id)
`

type SearchRoomParams struct {
	Price         float64            `json:"price"`
	StGeogpoint   interface{}        `json:"st_geogpoint"`
	StGeogpoint_2 interface{}        `json:"st_geogpoint_2"`
	FromTime      pgtype.Timestamptz `json:"from_time"`
	FromTime_2    pgtype.Timestamptz `json:"from_time_2"`
	RoomType      Roomtype           `json:"room_type"`
}

func (q *Queries) SearchRoom(ctx context.Context, arg SearchRoomParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, searchRoom,
		arg.Price,
		arg.StGeogpoint,
		arg.StGeogpoint_2,
		arg.FromTime,
		arg.FromTime_2,
		arg.RoomType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.RoomNumber,
			&i.HotelID,
			&i.RoomTypeID,
			&i.Floor,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoom = `-- name: UpdateRoom :one
update rooms set status =$1
where id= $2  
returning id, room_number, hotel_id, room_type_id, floor, status, created_at, updated_at
`

type UpdateRoomParams struct {
	Status RoomStatus  `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom, arg.Status, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.RoomNumber,
		&i.HotelID,
		&i.RoomTypeID,
		&i.Floor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
