db:
  conn: postgresql://root@db:26257/defaultdb?sslmode=disable
  dbname: reservation
token:
  expire_after: 100m
reservation:
  cancellation_time: 5m
paypal:
	baseURL: https://api.sandbox.paypal.com
	returnURL: https://yourwebsite.com/success
	cancelURL: https://yourwebsite.com/cancel